New Rule: Impersonation Suspected supplier lookalike
sublime-security/sublime-rules pull request #1262
Opened 2024-01-29 02:34 UTC by morriscode

2024-01-29 02:39 UTC, morriscode commented
/update-test-rules

2024-01-30 14:06 UTC, morriscode commented
This matches 2 known samples of supplier impersonation attempting to intercept or redirect payments. 
It has not fired at all in the last day of testing. It's a relatively over tightened rule and because of that it should be fairly safe to deploy. I don't expect high volume but I do expect when it fires, it will be worth having. 

I'm also working on other variation using this logic that are perhaps slightly looser. lmk what you want to do with this one.

2024-01-30 22:17 UTC, aidenmitchell approved these changes

2024-01-30 22:19 UTC, aidenmitchell requested changes

2024-01-30 22:19 UTC, aidenmitchell commented on detection-rules/impersonation_suspected_supplier_payment_request.yml
> +description: "This rule detects supplier impersonation by checking for: similar but not identical linked domains to the sender, non-freemail senders using freemail infrastructure, sender domains less
```suggestion
description: "This rule detects supplier impersonation by checking for: similar linked domains to the sender, non-freemail senders using freemail infrastructure, sender domains less than 90 days old, unsolicited communication or no prior interaction with the reply-to address, and a suspicious body."
```

2024-01-30 22:20 UTC, aidenmitchell approved these changes

2024-01-30 22:27 UTC, merged