New rule: Google Calendar invite linking to an open redirect from an untrusted freemail sender
sublime-security/sublime-rules pull request #1440
Opened 2024-04-01 15:51 UTC by aidenmitchell

2024-09-11 16:04 UTC, aidenmitchell commented
/update-test-rules

2024-09-30 16:29 UTC, zoomequipd commented on detection-rules/link_gcal_invite_open_redirect.yml
> +  and not profile.by_sender().any_false_positives
IIRC there was some discussion about how any_false_positives isn't suppose to be used by itself. 

convo here: https://github.com/sublime-security/sublime-rules/pull/1773#discussion_r1713834810

2024-10-04 15:18 UTC, aidenmitchell commented
No hits in shared samples

2024-10-08 14:08 UTC, zoomequipd requested changes

2024-10-08 14:08 UTC, zoomequipd commented on detection-rules/link_gcal_invite_open_redirect.yml
> +            any(beta.linkanalysis(.).final_dom.links,
update to non-beta version?

2024-10-10 12:16 UTC, zoomequipd approved these changes

2024-10-10 16:19 UTC, merged