Create open_redirect_artisteer.yml
sublime-security/sublime-rules pull request #1495
Opened 2024-04-30 19:43 UTC by aidenmitchell

2024-05-02 12:44 UTC, morriscode commented
/update-test-rules

2024-09-11 16:03 UTC, aidenmitchell commented
/update-test-rules

2024-09-11 16:03 UTC, aidenmitchell commented
https://platform.sublime.security/hunts/1ff9dfa9-dc41-4cb8-b295-1d6b3cf24d6b

2024-09-11 17:33 UTC, zoomequipd requested changes
redirect is still active/working.

2024-09-11 17:33 UTC, zoomequipd commented on detection-rules/open_redirect_artisteer.yml
> +          and strings.icontains(.href_url.query_params, 'redirect_url')
looks like `p=affr` is required for the redirect to work.  
might also add `=` to the end of `redirect_url`

```
and strings.icontains(.href_url.query_params, 'redirect_url=')
and strings.icontains(.href_url.query_params, 'p=affr')
```

Examples: 
- doesn't work `http://www.artisteer.com/?redirect_url=https://example.com`
- doesn't work `http://www.artisteer.com/?p=AAAA&redirect_url=https://example.com`
- works `http://www.artisteer.com/?p=affr&redirect_url=https://example.com`

2024-09-11 17:33 UTC, zoomequipd requested changes
redirect is still active/working.

2024-09-11 17:46 UTC, zoomequipd approved these changes

2024-09-11 17:48 UTC, merged