Create spam_image_hidden_element.yml
sublime-security/sublime-rules pull request #1668
Opened 2024-06-17 19:56 UTC by zoomequipd

# Description
Adding detection for emails with observed body html template that uses a single image as body content and hides the rest of the html.

# Associated samples
- [Sample 1](https://platform.sublimesecurity.com/messages/c4f3fe0398d704f0d88db9988ca5d85cc2452ae74581b2c3492a2b9bb72da121)
- [Sample 2](https://platform.sublimesecurity.com/messages/e9feb03520daad74e2fe1dcda262cbb0b54c68ab012a41dd1cc6edf27e1a28b3)
- [Sample 3](https://platform.sublimesecurity.com/messages/00d31f1821cd55ea499d35b7df6c0f89f3b64acb9909b1ffe4dea02fe43f49c2)

## Associated hunts
- [Hunt 1](https://platform.sublimesecurity.com/hunts/a34d973e-74f6-443f-9dae-ed983063cd99)

2024-06-17 19:59 UTC, morriscode commented
/update-test-rules

2024-06-20 14:01 UTC, zoomequipd commented
baking

2024-06-27 16:52 UTC, zoomequipd commented
still baking

2024-06-28 18:42 UTC, zoomequipd commented
looking ok, not a lot of volume, but all TPs

2024-07-01 17:48 UTC, morriscode requested changes
Left a suggestion, other than that looks great!

2024-07-01 17:48 UTC, morriscode commented on detection-rules/spam_image_hidden_element.yml
> +  - "Content analysis"
```suggestion
  - "Content analysis"
  - "HTML analysis"
  - "Sender analysis"
```

2024-07-02 19:49 UTC, zoomequipd commented
/udpate-test-rules

2024-07-03 15:24 UTC, morriscode approved these changes

2024-07-03 20:16 UTC, zoomequipd commented
/update-test-rules

2024-07-08 14:32 UTC, zoomequipd commented
/update-test-rules

2024-07-09 01:12 UTC, morriscode approved these changes

2024-07-09 19:55 UTC, zoomequipd commented
looking good. pushing.

2024-07-09 19:56 UTC, merged