New Rule: Attachment: RTF file with suspicious link
sublime-security/sublime-rules pull request #1792
Opened 2024-07-29 21:46 UTC by morriscode

# Description

New Rule detecting RTF File attachments (direct or within archive) with suspicious links
Exclusions made for image links

# Associated samples

[Sample](https://platform.sublimesecurity.com/messages/7aefecc7df80eed02d0b3517128faef7b34195ea55e8b57fa1eba707988162b8)

2024-07-29 21:46 UTC, morriscode commented
/update-test-rules

2024-07-31 15:16 UTC, morriscode commented
/update-test-rules

2024-08-02 13:26 UTC, morriscode commented
The newer test rules dashboard is confused by this rule getting a name change. The old one shows one hit. 
In my testing however this is knocking down hundreds in sharedEML's and is probably tight enough with the scope on RTF's to go out.

2024-08-02 16:27 UTC, zoomequipd requested changes

2024-08-02 16:27 UTC, zoomequipd commented on detection-rules/attachment_rtf_file_with_suspicious_link.yml
> +                                  strings.icontains(..url, .email.email)
Do you want `..url` here or `.url`?

2024-08-02 16:30 UTC, zoomequipd commented on detection-rules/attachment_rtf_file_with_suspicious_link.yml
> +                                  strings.icontains(..url, .email.email)
`..url` is correct

2024-08-02 16:30 UTC, zoomequipd approved these changes

2024-08-02 16:37 UTC, merged