Update impersonation_dropbox.yml
sublime-security/sublime-rules pull request #1796
Opened 2024-07-30 17:52 UTC by aidenmitchell

# Description

Adding link check to flag on display URL == dropbox.com but with a mismatch.

# Associated samples

- https://platform.sublimesecurity.com/messages/3dca3712fbb6994e5a0401f9330ed444e640c9a32bfd3feadc0d0bbb2fea984d

2024-08-02 13:40 UTC, morriscode commented
/update-test-rules

2024-08-02 13:41 UTC, morriscode commented
Added to test rules, I'm guessing this is fine but just wanted to double check since a mismatch could be for a few reasons?

2024-08-07 21:09 UTC, zoomequipd commented
looks OK in test rules 3 new matches compared to existing version (4 matches total) but, I think there's a chance of FPs on URL rewriters for which there are not decoders. I did run a hunt, which turned up nothing though, so maybe not as big of a concern as I think. 

https://platform.sublime.security/hunts/8e094495-eec7-4e0c-9902-eef441df9f5b

2024-08-07 21:51 UTC, aidenmitchell commented
Just in case, I added a Mimecast negation.

2024-08-07 22:12 UTC, zoomequipd requested changes

2024-08-07 22:12 UTC, zoomequipd commented on detection-rules/impersonation_dropbox.yml
> +           and not .href_url.domain.root_domain == "mimecast.com"
`mimecastprotect.com`?

2024-08-07 22:54 UTC, zoomequipd approved these changes

2024-08-07 22:57 UTC, merged