Update impersonation_fedex.yml
sublime-security/sublime-rules pull request #1956
Opened 2024-09-27 17:55 UTC by peterdj45

# Description

Adding additional sender display name criteria

# Associated samples

- https://eu.platform.sublime.security/messages/5f19d6ae324f35118f6da9059c9b0aa160d1e11c73ad57526f790bb526686d47
- https://platform.sublime.security/messages/b97144a4da63f6f3098e63b82ff84e059f7cc5856fcede702c05542f2df37134

2024-09-30 13:35 UTC, zoomequipd requested changes

2024-10-01 22:25 UTC, peterdj45 commented on detection-rules/impersonation_fedex.yml
> +    or regex.icontains(sender.display_name, '^Fed-ex|Fedex')
My intent was to enforce the `startswith` logic on both, so that makes sense! Thanks for catching that 😄

2024-10-01 22:31 UTC, peterdj45 commented
/mql-mimic-exempt 524984

Unrelated sample/rule firing...

2024-10-02 14:18 UTC, zoomequipd approved these changes

2024-10-03 21:00 UTC, merged