Create link_adobe_share_unsoliticed_sender.yml
sublime-security/sublime-rules pull request #1996
Opened 2024-10-09 23:00 UTC by zoomequipd

# Description

Add new coverage from observed abused Adobe message which link to an Adobe hosted file which links to cred phishing. 

# Associated samples

Sample was provided privately

2024-10-09 23:05 UTC, zoomequipd commented
/update-test-rules

2024-10-16 18:17 UTC, zoomequipd commented
looking good, very low volume based on telemetry data

2024-10-17 15:38 UTC, aidenmitchell requested changes

2024-10-17 15:38 UTC, aidenmitchell commented on detection-rules/link_adobe_share_unsoliticed_sender.yml
> +description: "This attack surface reduction rule matches on message from Adobe which was sent by an email address (as determined by the sender display name) which doesn't appear to have a relationshi
```suggestion
description: "This attack surface reduction rule matches on messages from Adobe which were sent by an email address (as determined by the sender display name) which doesn't appear to have a relationship with the recipient organization."
```

2024-10-17 16:30 UTC, zoomequipd commented
going to rework this based on customer feedback

2024-10-17 18:51 UTC, aidenmitchell approved these changes

2024-10-24 02:51 UTC, merged