Create brand_impersonation_siriusxm.yml
sublime-security/sublime-rules pull request #2025
Opened 2024-10-18 16:27 UTC by aidenmitchell

# Description

Impersonation of the broadcasting corporation SiriusXM.

# Associated samples

- https://platform.sublime.security/messages/a68684e74cddcaeb5e66ca2ac973f079ddf57a5bfeaa3276551f8581518bb40e

2024-10-23 15:34 UTC, aidenmitchell commented
Looks good in test-rules, low volume

2024-10-24 13:59 UTC, zoomequipd requested changes
some feedback based on hunts

2024-10-24 13:59 UTC, zoomequipd commented on detection-rules/brand_impersonation_siriusxm.yml
> +name: "Brand impersonation: SiriusXM"
```suggestion
name: "Brand Impersonation: SiriusXM"
```

2024-10-24 13:59 UTC, zoomequipd commented on detection-rules/brand_impersonation_siriusxm.yml
> +      sender.email.domain.root_domain in ('siriusxm.com')
```suggestion
      sender.email.domain.root_domain in ('siriusxm.com', 'siriusxmmedia.com', 'siriusxm.ca')
```

2024-10-24 13:59 UTC, zoomequipd commented on detection-rules/brand_impersonation_siriusxm.yml
> +    sender.email.domain.root_domain not in ('siriusxm.com')
```suggestion
    sender.email.domain.root_domain not in ('siriusxm.com', 'siriusxmmedia.com', 'siriusxm.ca')
```

2024-10-25 01:26 UTC, zoomequipd approved these changes

2024-10-25 17:56 UTC, merged