Create credential_phishing_cross_site_scripting_in_sub.yml
sublime-security/sublime-rules pull request #2037
Opened 2024-10-22 22:06 UTC by morriscode

# Description

This rule detects Cross-Site Scripting (XSS) attempts within email subjects. It bypasses messages from highly trusted domains unless they fail authentication. However, the rule remains flexible, triggering even for trusted domains when emails are sent from Google Groups, ensuring thorough protection against potential threats while minimizing false positives.

## Associated hunts

- [Hunt 1](https://platform.sublime.security/hunts/8f1cd31b-346d-4449-9b65-b2c482ad097c)

2024-10-22 22:06 UTC, morriscode commented
/update-test-rules

2025-01-29 18:18 UTC, morriscode commented
This somehow has 0 hits despite a fruitful hunt, it appears to be in the test-rules table..

2025-02-10 20:31 UTC, zoomequipd requested changes

2025-02-10 20:40 UTC, zoomequipd commented on detection-rules/credential_phishing_cross_site_scripting_in_sub.yml
> +  and regex.contains(subject.subject, '(?:&#?[a-zA-Z0-9]+;|%[0-9A-Fa-f]{2}|\\[xu][a-fA-F0-9]{2,4}|[\x22\x27](?:>|&gt;)|(?:<|&lt;)\/?(?:[a-z]+|[A-Z]+)|\\[^\\a-zA-Z0-9])'))
```suggestion
  and regex.contains(subject.subject, '(?:&#?[a-zA-Z0-9]+;|%[0-9A-Fa-f]{2}|\\[xu][a-fA-F0-9]{2,4}|[\x22\x27](?:>|&gt;)|(?:<|&lt;)\/?(?:[a-z]+|[A-Z]+)|\\[^\\a-zA-Z0-9])')
```

2025-02-12 15:19 UTC, zoomequipd commented
/update-test-rules

2025-02-12 18:01 UTC, zoomequipd approved these changes

2025-02-13 04:00 UTC, merged