Create abuse_quickbooks_impersonation_intuit.yml
sublime-security/sublime-rules pull request #2054
Opened 2024-10-25 14:57 UTC by zoomequipd

# Description

Add coverage for observed Quickbooks Abuse

# Associated samples

- [Write Up and Sample](https://www.notion.so/sublimesecurity/EXTERNAL-Invoice-INTUITS46-eml-12a04655fc9d80c2bef4c600498d5191?pvs=4)

## Associated hunts

2024-11-04 22:28 UTC, zoomequipd commented
/update-test-rules

2024-11-14 22:02 UTC, zoomequipd commented
No shared samples, looks low volume.  marking for review

2024-12-13 18:08 UTC, aidenmitchell requested changes

2024-12-13 18:08 UTC, aidenmitchell commented on detection-rules/abuse_quickbooks_impersonation_intuit.yml
> +name: "Brand Impersonation: QuickBooks Notification From Inuit Themed Company Name"
```suggestion
name: "Brand Impersonation: QuickBooks Notification From Intuit Themed Company Name"
```

2024-12-13 18:08 UTC, aidenmitchell commented on detection-rules/abuse_quickbooks_impersonation_intuit.yml
> +description: "This detection rule matches on QuickBooks notifications that feature company names impersonating Inuit and Quickbooks"
```suggestion
description: "This detection rule matches on QuickBooks notifications that feature company names impersonating Intuit and QuickBooks."
```

2024-12-13 18:08 UTC, aidenmitchell commented on detection-rules/abuse_quickbooks_impersonation_intuit.yml
> +                       '<p class="companyName info-line" style="margin: 0; line-height: 1.5em; font-weight: 600;">.*(?:Inuit|Quickbooks).*</p></div>'
```suggestion
                       '<p class="companyName info-line" style="margin: 0; line-height: 1.5em; font-weight: 600;">.*(?:Intuit|Quickbooks).*</p></div>'
```

2024-12-13 21:19 UTC, aidenmitchell approved these changes

2024-12-16 15:09 UTC, merged