Create spam_item_giveaway.yml
sublime-security/sublime-rules pull request #2095
Opened 2024-11-07 03:46 UTC by zoomequipd

# Description

Add coverage to the return of the Item Giveaway spam

## Associated hunts

- [Hunt 1](https://platform.sublime.security/hunts/9ceecacf-f848-4169-8a87-43c3be08e071)

2024-11-07 03:47 UTC, zoomequipd commented
/update-test-rules

2024-11-19 22:30 UTC, zoomequipd commented
no hits in test, good hunt, i'm sure these actors will come back

2024-11-25 14:38 UTC, morriscode requested changes

2024-11-25 14:38 UTC, morriscode commented on detection-rules/spam_item_giveaway.yml
> +description: "This detection rule matches on observed html templates impersonating multiple popular brands used to deliver spam.  Often the lure leverages a them of item giveways or a chance to win a
```suggestion
description: "This detection rule matches on observed html templates impersonating multiple popular brands used to deliver spam.  Often the lure leverages a theme of item giveaways or a chance to win an item for completing a survey."
```

2024-12-02 23:06 UTC, morriscode approved these changes

2024-12-02 23:06 UTC, morriscode approved these changes

2025-01-02 22:52 UTC, merged