Create impersonation_benefits_enrollment.yml
sublime-security/sublime-rules pull request #2130
Opened 2024-11-18 19:54 UTC by aidenmitchell

# Description

Detects messages about benefit enrollment periods and healthcare selections from external senders that contain urgent language or requests for action. Excludes legitimate HR communications, marketing mailers, and trusted sender domains with valid authentication.

# Associated samples
- https://platform.sublime.security/messages/1b26393952d1c7d89cecab9ae5fade195c5d6e8c9c9524006471047ca09eba8b

2024-11-18 19:54 UTC, aidenmitchell commented
/update-test-rules

2024-11-22 16:54 UTC, aidenmitchell commented
/update-test-rules

2024-12-05 18:03 UTC, aidenmitchell commented
/update-test-rules

2024-12-10 01:17 UTC, peterdj45 requested changes
found a few samples in the wild using malicious attachments with empty/benign subjects and message body.

- https://platform.sublime.security/messages/f28905d065c6a8ac54109c8c850d2a24e27a27fc651061abf5c135e23c51ec15 (body.current_text comes back as null)
- https://platform.sublime.security/messages/b84df9f811c52dea9327dceccb98fc7b0f455bd6013df933bb5ec19d826bcdf1
- https://platform.sublime.security/messages/4139cb3009eba87cf128840f2fc25b7d5389df72fc025f9b8578ae4d1f19a8f6
- https://platform.sublime.security/messages/688d19813d7d760f44100fe7480b1d80db36879cc3a474497077d3a193f1f82d
- https://platform.sublime.security/messages/e09bc9481c23dce2455a4c499bef4648b401bf7ad09c3bc1dbf615c415cc219d

2024-12-10 01:17 UTC, peterdj45 commented on detection-rules/impersonation_benefits_enrollment.yml
> +    (length(body.current_thread.text) < 250 and length(attachments) == 1)
```suggestion
    (
     length(body.current_thread.text) < 250 and length(attachments) == 1
     or length(body.current_thread.text) is null and length(attachments) == 1
    ),
```
handle null values in body.current_thread.text again

2024-12-10 01:17 UTC, peterdj45 commented on detection-rules/impersonation_benefits_enrollment.yml
> +  )
```suggestion
    // lure in attachment
    (
      any(attachments,
          (.file_type in $file_types_images or .file_type in ("pdf", "docx", "doc"))
          and any(filter(file.explode(.), .scan.ocr.raw is not null),
                  (
                    any(ml.nlu_classifier(.scan.ocr.raw).intents,
                        .name != "benign"
                    )
                    or any(ml.nlu_classifier(.scan.ocr.raw).entities,
                            .name in ("urgency", "request")
                    )
                  )
              )
          )
      )
  )
```
detect lures in attachment

2024-12-10 01:17 UTC, peterdj45 commented on detection-rules/impersonation_benefits_enrollment.yml
> +  and length(body.current_thread.text) < 2500
```suggestion
  and length(body.current_thread.text) < 2500 or length(body.current_thread.text) is null
```
handle null values in body.current_thread.text

2024-12-10 17:43 UTC, aidenmitchell commented
@peterdj45 is going to open a PR against this PR for these changes, makes for an easier time in GH... lol

2024-12-10 18:01 UTC, aidenmitchell commented
/update-test-rules

2025-01-10 17:10 UTC, aidenmitchell commented
/update-test-rules

2025-01-29 00:27 UTC, zoomequipd approved these changes

2025-01-30 21:59 UTC, zoomequipd approved these changes

2025-01-30 22:00 UTC, merged